plugin/RunalyzePluginPanel_Prognose/Plot.Form.php
plugin/RunalyzePluginPanel_Rechenspiele/Plot.Form.php
plugin/RunalyzePluginTool_DatenbankCleanup/JobLoop.php

- recalculate only for running
- for plots show only running and use_vdot
more work may be needed

fix: vdot stuff

---

inc/system/class.AccountHandler.php
inc/system/schemes/set.emptyValues.php

left a few words for translation from German to English

initialize new user's config values - fix #1200

---

inc/core/Model/Activity/Clothes/Object.php

Clothes have to be saved as e.g. "28,31,32" instead of "28, 31, 32" such that `FIND_IN_SET` will work (as in weather/clothes statistics).

fix clothes for FIND_IN_SET

---

inc/class.InstallerUpdate.php

I found it useful to have this available from the list of possible updates after placing the git head version over my previous one.

add database update 2.0 to 2.1 to selection list for update.php

---

inc/import/parser/class.ParserTCXSingle.php

Notes should be added from TCX file when exported from Polar Flow.

Add Notes from TCX file (export from Polar Flow)

---

inc/import/parser/class.ParserXMLpolarSingle.php

Add note and comment from note and name elements.

Add note and comment

---

inc/class.Dataset.php
inc/plugin/class.PluginStat.php
lib/less/leaflet.less
lib/less/runalyze-installer.less
lib/less/runalyze-mobile.less
lib/less/runalyze-overlay.less
lib/less/runalyze-style.css
lib/less/runalyze-training.less
plugin/RunalyzePluginStat_Statistiken/class.RunalyzePluginStat_Statistiken.php

* should be tested in view of ground contact time and vertical oscillation
* maybe needs some testing for swimming data, other sports

fixes for #1427 and #1420

---

plugin/RunalyzePluginStat_MonthlyStats/class.RunalyzePluginStat_MonthlyStats.php

Added report for "all sports"
Added additional metrics: calories, trim, elevation, number of activities

Extended monthly stat

---

inc/core/View/Activity/Plot/Series/Pace.php

Fixes a bug introduced in e1c4075.

Fix pace axis

---

build/scripts.js
lib/runalyze.lib.feature.js
plugin/RunalyzePluginPanel_Rechenspiele/Plot.Form.php
plugin/RunalyzePluginPanel_Sports/class.RunalyzePluginPanel_Sports.php
plugin/RunalyzePluginPanel_Ziele/class.RunalyzePluginPanel_Ziele.php

Calculate date from index the same way as we calculated index from date, not via day of year.

Fix dates in form plot.

---

inc/core/Model/Sport/Entity.php
inc/core/Profile/FitSdk/SportProfile.php
inc/core/Profile/Mapping/AbstractMapping.php
inc/core/Profile/Sport/AbstractSport.php
inc/core/Profile/Sport/Cycling.php
inc/core/Profile/Sport/Generic.php
inc/core/Profile/Sport/Hiking.php
inc/core/Profile/Sport/Mapping/FitSdkMapping.php
inc/core/Profile/Sport/ProfileInterface.php
inc/core/Profile/Sport/Rowing.php
inc/core/Profile/Sport/Running.php
inc/core/Profile/Sport/SportProfile.php
inc/core/Profile/Sport/Swimming.php
inc/core/Profile/Weather/WeatherConditionProfile.php
inc/core/Util/AbstractEnumFactoryTrait.php
tests/inc/core/Profile/Sport/Mapping/FitSdkMappingTest.php
tests/inc/core/Util/AbstractEnumFactoryTraitTest.php

prepare fixed sport types

---

README.md

Links to Install and Update resulted in a 404, this PR fixes this.

fixes links in readme

---

app/config/security.yml

Fixes #1950.
Waiting for approval by @mipapo.

disable firewall for update/install

---

call/perl/Garmin/FIT.pm

update fit parser to v0.23

---

.travis.yml
app/config/config.yml
app/config/config_test_empty.yml
src/CoreBundle/Entity/Route.php
tests/CoreBundle/Command/InstallDatabaseCommandTest.php

+ let travis try to create database based on our entities

fix route entity

---

inc/import/class.ImporterFactory.php
inc/import/class.ImporterWindow.php
inc/import/class.ImporterWindowTabFormular.php
inc/import/class.MultiImporterFormular.php
inc/import/tpl/tpl.Importer.upload.php
src/CoreBundle/Controller/ActivityController.php

fix import for files with semicolon

---

app/Resources/views/_macro/utilities.html.twig
app/Resources/views/my/statistics/base.html.twig
app/Resources/views/my/statistics/monthly-stats/base.html.twig
app/config/services.yml
lib/runalyze.lib.statistics.js
plugin/RunalyzePluginStat_MonthlyStats/class.RunalyzePluginStat_MonthlyStats.php
src/CoreBundle/Component/Configuration/Category/General.php
src/CoreBundle/Component/Statistics/MonthlyStats/AnalysisData.php
src/CoreBundle/Component/Statistics/MonthlyStats/AnalysisSelection.php
src/CoreBundle/Controller/PluginController.php
src/CoreBundle/Entity/TrainingRepository.php
src/CoreBundle/Services/PrivacyGuard.php
src/CoreBundle/Services/Selection/Selection.php
src/CoreBundle/Services/Selection/SportSelectionFactory.php
src/CoreBundle/Services/TokenStorageAwareServiceTrait.php
src/CoreBundle/Twig/DisplayableTime.php
src/CoreBundle/Twig/DisplayableValue.php

There are no known issues, but I did only a short check with my data (e.g. tried to show monthly stats for some different sport types and all analysis types).
Still, some easy unit tests could be added.

refactor monthly stats plugin to symfony world

---

src/CoreBundle/Component/Statistics/MonthlyStats/AnalysisData.php
src/CoreBundle/CoreBundle.php
src/CoreBundle/Entity/TrainingRepository.php
src/CoreBundle/Form/Settings/ChangeMailType.php
src/CoreBundle/Form/Tools/DatabaseCleanupType.php
src/CoreBundle/Twig/ConfigurationExtension.php
src/CoreBundle/Twig/DisplayablePace.php
src/CoreBundle/Twig/HtmlExtension.php
src/CoreBundle/Twig/UtilityExtension.php
src/CoreBundle/Twig/ValueExtension.php
src/CoreBundle/Validator/Constraints/ContainsDisposableMailAddressValidator.php
src/CoreBundle/Validator/Constraints/IsValidTimezoneValidator.php
tests/CoreBundle/Component/Account/RegistrationTest.php
tests/CoreBundle/Component/Statistics/MonthlyStats/AnalysisDataTest.php
tests/CoreBundle/Entity/AccountRepositoryTest.php
tests/CoreBundle/Services/Configuration/ConfigurationManagerTest.php
tests/CoreBundle/Services/Selection/SelectionTest.php
tests/CoreBundle/Services/Sha256SaltedEncoderTest.php
tests/CoreBundle/Twig/HtmlExtensionTest.php
tests/CoreBundle/Twig/UtilityExtensionTest.php
tests/CoreBundle/Twig/ValueExtensionTest.php

Need to test this first on travis, as my local environment throws an error that seems to be unrelated to current changes.

add a few unit tests

---

gulpfile.js
lib/less/runalyze-container.less
lib/less/runalyze-headline.less
lib/less/runalyze-style.less
package.json
web/assets/v2.x/vendor/iconvault-forecast/iconvault-forecast.css

No idea why paths to images have to be 'wrong', but for me everything works now.

fix problems with gulp-clean-css

---

src/CoreBundle/Controller/My/BodyValuesController.php
src/CoreBundle/Entity/User.php
src/CoreBundle/Form/BodyValuesType.php
src/CoreBundle/Form/Type/AbstractUnitBasedType.php
src/CoreBundle/Form/Type/DistanceType.php
src/CoreBundle/Form/Type/EnergyType.php
src/CoreBundle/Form/Type/TemperatureType.php
src/CoreBundle/Form/Type/WeightType.php
tests/CoreBundle/Form/Type/AbstractUnitBasedTypeTest.php

fix body values form for decimals

---

inc/core/Parameter/Application/WeekStart.php
inc/draw/class.PlotSumData.php
inc/draw/class.PlotWeekSumData.php

fix weekly plot

---

inc/import/class.ImporterFactory.php
src/CoreBundle/Command/ActivityBulkImportCommand.php

In theory, this should fix #2097.

fix import command for laps

---

inc/core/Model/Trackdata/Entity.php
inc/core/Model/Trackdata/Loop.php
inc/core/View/Activity/Plot/Series/GradeAdjustedPace.php
inc/core/View/Activity/Plot/Series/PaceCumulativeAverage.php
tests/inc/core/Data/Laps/CalculatorTest.php
tests/inc/core/Model/Trackdata/LoopTest.php

Fix page average in loops

---

src/CoreBundle/Controller/Settings/SportController.php

fix sport settings for adding custom sport

---

inc/core/View/Leaflet/Map.php
inc/core/View/Leaflet/Route.php

fix js code for maps for some languages

---

app/Resources/views/_include/js_init.html.twig
app/Resources/views/base_logged_in.twig
app/Resources/views/shared/base.html.twig
app/config/config.yml

Fix: Mapbox Outdoor is not visible in public activity

---

lib/less/runalyze-headline.less

fix width of notifications menu

---

inc/core/Sports/Performance/Model/TsbModel.php
tests/inc/core/Sports/Performance/Model/TsbModelTest.php

fix rest days in tsb model for low ctl values

---

app/DoctrineMigrations/Version20170430165002.php
inc/install/structure.sql

fix notification constraint

---

app/Resources/views/shared/athlete/base.html.twig
app/config/services.yml
composer.json
composer.lock
inc/core/View/Activity/Feed.php
src/CoreBundle/Controller/SharedController.php
src/CoreBundle/Entity/TrainingRepository.php

- only if public list is public
- activities are only linked if they are public too
Only following values are in the feed:
Sport, Activity type, duration, distance, pace

Athlete activity rss feed

---

app/DoctrineMigrations/Version20171201214532.php
app/Resources/views/settings/dataset.html.twig
inc/core/Dataset/Configuration.php
inc/core/Dataset/DefaultConfiguration.php
inc/core/Dataset/Keys/AbstractKey.php
inc/core/Dataset/Keys/Daytime.php
inc/core/Dataset/Keys/Tools.php
inc/core/Dataset/Query.php
inc/core/Profile/View/DataBrowserRowProfile.php
inc/core/Profile/View/DatasetPrivacyProfile.php
inc/core/View/Dataset/Table.php
inc/install/structure.sql
src/CoreBundle/Entity/Dataset.php
src/CoreBundle/Form/Settings/DatasetType.php
tests/inc/core/Dataset/ConfigurationTest.php

Hide dataset keys on public page if wanted

Dataset privacy

---

app/DoctrineMigrations/Version20180113231353.php
app/DoctrineMigrations/Version20180116214552.php
app/Resources/views/activity/form.html.twig
app/config/services.yml
inc/core/Configuration/Category/ActivityForm.php
inc/core/Model/Activity/Entity.php
inc/training/view/section/class.SectionMiscellaneousRow.php
lib/runalyze.lib.activity.form.js
src/CoreBundle/Component/Configuration/Category/ActivityForm.php
src/CoreBundle/Controller/Activity/CreateController.php
src/CoreBundle/Controller/Activity/EditController.php
src/CoreBundle/Entity/Training.php
src/CoreBundle/EntityListener/ActivityListener.php
src/CoreBundle/Form/ActivityType.php
src/CoreBundle/Form/Type/PowerType.php
src/CoreBundle/Form/Type/SportChoiceType.php

+ save whether power has been calculated or not
+ lock avg. power in form if it's based on time series

Fix power in activity form

---

app/Resources/public/js/views/race-performance-chart-view.js
app/Resources/views/my/raceresult/performance_chart.html.twig
src/CoreBundle/Controller/Internal/Data/RaceResultsController.php
src/CoreBundle/Entity/PluginConf.php
src/CoreBundle/Entity/PluginConfRepository.php

- respect fun races in race results performance chart
- add notices to chart view

fixes for performance chart

---

src/CoreBundle/Controller/My/RaceResultController.php
src/CoreBundle/Services/LegacyCache.php

via https://forum.runalyze.com/viewtopic.php?t=962&p=4156

fix race result cache in old factory
